<a href="https://colab.research.google.com/github/ErikVegaC/OTO-O2024/blob/main/T08_DISTRIBUCIONES_DE_PROBABILIDAD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **T08 -   Distribuciones de probabilidad**

### Erik Gabriel Vega Cervantes
### Expediente 745264
### A 23 de octubre de 2024

1. Un proyecto de construcción está por comenzar. Se hace la compra de los materiales y el proveedor dice que en promedio tardan una semana con una desviación de 3 días en llegar. Una vez llegados los materiales se tarda entre 3 y 5 semanas en construir (uniforme). Después de la construcción se deben esperar 3 días antes de empezar a pintar, y toma 6 días en promedio con 2 días de desviación estándar hacerlo.

a) Describe en una celda qué distribución usarías para cada paso del proceso



$a_1$ para estimar el tiempo de entrega usaría una distribucion normal considerando los datos dados, ya que habla de una estimación de tiempo y que puede variar debido a la concentracion de datos con la desviación.

$a_2$ para estimar el tiempo de construcción usaría una distribución uniforme, ya que no menciona alguna variación u concentración de datos, es decir, tienen la misma probabilidad.

$a_3$ para estimar el tiempo de pintura nuevamente usaría la distribución normal considerando los dias promedio(media) y usando la desviación para determinar la concentracion de los datos.



b) Simula cada paso en el proceso un millón de veces



In [29]:
entrega_m = 7
entrega_dev = 3

const_t_min = 21
const_t_max = 35


pintura_m = 6
pintura_dev = 2


n = 1000000

t_entrega = np.random.normal(entrega_m, entrega_dev,n)
t_construccion = np.random.uniform(const_t_min, const_t_max,n)
t_pintura = np.random.normal(pintura_m,pintura_dev,n)


t_entrega,t_construccion, t_pintura

(array([ 1.73779923, 10.1471205 ,  3.81301522, ...,  7.20299104,
         5.03500968,  0.19988177]),
 array([24.64394932, 28.98450101, 26.56737277, ..., 25.97808156,
        34.83538093, 28.16638152]),
 array([5.88475557, 4.87208781, 8.78968736, ..., 5.04971308, 5.16256102,
        5.56435514]))

c) Agrupa las simulaciones de cada paso para tener la simulación del proceso completo


In [30]:
import numpy as np

entrega_m = 7
entrega_dev = 3

const_t_min = 21
const_t_max = 35

pintura_t = 3

pintura_m = 6
pintura_dev = 2

n = 1000000

t_entrega = np.random.normal(entrega_m, entrega_dev,n)
t_construccion = np.random.uniform(const_t_min, const_t_max,n)
t_pintura = np.random.normal(pintura_m,pintura_dev,n)


total_t = t_entrega + t_construccion + t_pintura + pintura_t
total_t

array([35.5957969 , 45.2988292 , 39.31764316, ..., 37.85644972,
       46.74811832, 40.79631918])


d) ¿Cuál es el tiempo promedio para de inicio-fin del proyecto?


In [23]:
print(f"El tiempo promedio de inicio-fin de el proyecto son: {np.ceil((total_t.mean()))} días")

El tiempo promedio de inicio-fin de el proyecto son: 44.0 días



e) De acuerdo a tus simulaciones, ¿cuál es el peor caso? ¿cuál es el mejor caso?



In [27]:
print(f"El peor caso de el tiempo total de la construcción son {int(np.ceil((np.min(total_t))))} días")
print(f"El mejor caso de el tiempo total de la construcción son {int(np.ceil((np.max(total_t))))} días")

El peor caso de el tiempo total de la construcción son 23 días
El mejor caso de el tiempo total de la construcción son 67 días


f) Si el proyecto se tiene que entregar a más tardar en 50 días o se tiene que pagar una compensación al cliente, ¿cuál es la probabilidad de que el proyecto se entregue a tiempo?



In [37]:
p_1 = np.mean(total_t <= 50) * 100

print(f"La probabilidad de que el proyecto se entregue a mas tardar en 50 dias es del {int(p)}%")

La probabilidad de que el proyecto se entregue a mas tardar en 50 dias es del 85%


g) ¿Cuál es la probabilidad de que el proyecto tome entre 20 y 40 días?

In [41]:
p_2 = np.mean((total_t >= 20) & (total_t <= 40) )
print(f"La probabilidad de que el proyecto se entregue entre 20 y 40 dias es del {int(p_2*100)}%")

La probabilidad de que el proyecto se entregue entre 20 y 40 dias es del 24%


2. Hay un elevador pequeño en una plaza donde se espera que entren máximo 4 personas a la vez, y su capacidad de peso para poder operar es de 300 kg. En el último censo se encontró que habían 378350 personas en la zona:

    - 185392 mujeres
    - 162690 hombres
    - 30268 personas que o prefirieron no dar la información o se identificaron como no binarias
    
El peso promedio medido en mujeres es de 70 kg con una desviación estándar de 11 kg. En los hombres se midió un peso promedio de 80 kg y una desviación estándar de 16 kg. En el tercer grupo se midió un peso promedio de 73 kg con una desviación estándar de 12 kg.

a) Si el elevador se llenara 10,000 veces, ¿cuántas de esas veces se excedería el peso permitido?

In [73]:
import numpy as np

peso_mujeres_prom = 70
peso_mujeres_std = 11

peso_hombres_prom = 80
peso_hombres_std = 16

peso_nobinarios_prom = 73
peso_nobinarios_std = 12


total_personas = 185392 + 162690 + 30268
prob_mujeres = 185392 / total_personas
prob_hombres = 162690 / total_personas
prob_nobinarios = 30268 / total_personas


n_viajes = 10000
capacidad_maxima = 300

excesos = 0

for _ in range(n_viajes):
    pesos = []
    for _ in range(4):
        grupo = np.random.choice(['mujer', 'hombre', 'nobinario'], p=[prob_mujeres, prob_hombres, prob_nobinarios])
        if grupo == 'mujer':
            peso = np.random.normal(peso_mujeres_prom, peso_mujeres_std)
        elif grupo == 'hombre':
            peso = np.random.normal(peso_hombres_prom, peso_hombres_std)
        else:
            peso = np.random.normal(peso_nobinarios_prom, peso_nobinarios_std)
        pesos.append(peso)


    if sum(pesos) > capacidad_maxima:
        excesos += 1

print(f"Se excedió del peso {excesos} de las 10,000 veces")


Se excedió del peso 4758 de las 10,000 veces


b) ¿Qué peso total tendría que soportar el elevador si se quiere que el 95% de las veces que se llene no se exceda el peso permitido?

In [75]:

pesos_totales = []

for i in range(n_viajes):
    pesos = []
    for i in range(4):
        grupo = np.random.choice(['mujer', 'hombre', 'nobinario'], p = [prob_mujeres,prob_hombres,prob_nobinarios])
        if grupo == 'mujer':
            peso = np.random.normal(peso_mujeres_prom, peso_mujeres_std)
        elif grupo == 'hombre':
            peso = np.random.normal(peso_hombres_prom, peso_hombres_std)
        else:
            peso = np.random.normal(peso_nobinarios_prom, peso_nobinarios_std)
        pesos.append(peso)

    pesos_totales.append(sum(pesos))

pesos_totales = np.array(pesos_totales)

percentil_95 = np.percentile(pesos_totales, 95)
print(f"El peso total que el elevador debería soportar para no excederse en el 95% de los casos es: {percentil_95} kg")


El peso total que el elevador debería soportar para no excederse en el 95% de los casos es: 346.30871888749436 kg


3. Tienes diez dados justos. Si arrojas todos al mismo tiempo, ¿cuál es la probabilidad de que la suma de los dados sea múltiplo de 6?

In [124]:
dados = 10
n = 1000000
d = np.random.choice([1,2,3,4,5,6],(n,dados),p=[1/6,1/6,1/6,1/6,1/6,1/6])
sumas_lanzamiento = np.sum(d,1)

multiplo_6 = (sumas_lanzamiento % 6) == 0

print(f"La probabilidad de que la suma de los dados sea multiplo de 6 es del {multiplo_6.mean()*100}%")

La probabilidad de que la suma de los dados sea multiplo de 6 es del 16.5969%


4.  A y B juegan al siguiente juego: un número k del 1 al 6 es elegido, y A y B avientan el dado por turnos hasta que alguien consiga que el dado caiga en k. El ganador recibe $100.

In [142]:


import numpy as np


n = 100000
k = np.random.randint(1,7)


victorias_A = 0
victorias_B = 0

premio = 100

for i in range(n):
    while True:
        if np.random.randint(1, 7) == k:
            victorias_A += 1
            break
        if np.random.randint(1, 7) == k:
            victorias_B += 1
            break


prob_A_gana = victorias_A/n
prob_B_gana = victorias_B/n


valor_esperado_A= premio * prob_A_gana




a) ¿Cuál es la probabilidad de que el primer jugador gane?



In [144]:
print(f"La probabilidad de que el primer jugador gane es del {int(np.ceil(prob_A_gana*100))}%")

La probabilidad de que el primer jugador gane es del 55%


b) ¿Cuál es la probabilidad de que el segundo jugador gane?



In [145]:
print(f"La probabilidad de que el segundo jugador gane es del {int(np.ceil(prob_B_gana*100))}%")

La probabilidad de que el segundo jugador gane es del 46%


c) ¿Cuánto vale la pena pagar para ir primero?

In [147]:
print(f"Vale la pena pagar ${int(valor_esperado_A)}")

Vale la pena pagar $54
